### ISSUE TITLE
New release with the refresh token support?

### ISSUE THREAD

**Issue by drewish** [tzmfreedom/rustforce#1]
First off thanks for putting this out there. I'm new to rust and definitely not up to writing my own client. 

It seems like the refresh token support is only in master. Once I figure out how to source it from github I was able to test it out and it's working for me. Would you mind doing a new release to make it public? I'm happy to help with the docs if you'd like a PR.

**Comment by tzmfreedom** [comment]
Thank you for issue !
I published `0.1.2` which includes refresh function and update README.
https://crates.io/crates/rustforce
