### ISSUE TITLE
Simple GET for apexrest URIs

### ISSUE THREAD

**Issue by sempervictus** [tzmfreedom/rustforce#11]
While going over `client.rs` i noticed that GET requests are not public, which make linear REST requests into `<base_url>/services/apexrest` a bit problematic. I'm converting from Ruby code which uses the RestForce `#get` mechanism to pull from parameter-injected URIs in order to build a data set, is that something i can do with the publicly exposed methods or do i need to use a local copy of the crate and expose the `fn get` to crate users?

**Comment by tzmfreedom** [comment]
Fixed by https://github.com/tzmfreedom/rustforce/pull/12
So I'll close this issue. Thank you for reporting the issue!
