### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by ccakes** [tzmfreedom/rustforce#2]
Hey, looks like a great project! Any immediate plans to update this to use reqwest 0.10+ which would allow this to be used (easily) in an async/await codebase?

**Comment by tzmfreedom** [comment]
Thank you !
I didn't know async/await for rust with reqwest 0.10+.
I'll try to use it and apply it to rustforce 👍

**Comment by patnaikshekhar** [comment]
@ccakes we've now added async/await support.

**Comment by ccakes** [comment]
Legend - thanks for the hard work!
